#Prepare Zlib for compilation:
#
#./configure --prefix=/usr
#Compile the package:
#
#make
#To test the results, issue:
#
#make check
#Install the package:
#
#make install
#Remove a useless static library:
#
#rm -fv /usr/lib/libz.a
#8.6.2. Contents of Zlib
#Installed libraries:
#libz.so
#Short Descriptions
#libz
#
#Contains compression and decompression functions used by some programs
